### ISSUE TITLE
No location provided (how to debug)

### ISSUE THREAD

**Issue by AllesMeins** [microg/IchnaeaNlpBackend#50]
Unfortunately I can't get the location backend to work and I'm a bit lost to find the reason. I've installed the latest UnifiedNlp (GAPPS Version, since I've playstore installed), the XposedUnifiedNlp Module and the IchnaeaNlpBackend 1.4.0 configured and activated. According to the SelfTest everything is in order and should work but "No UnifiedNlp location was provided by the system within 10 seconds". 

Now I'm a bit lost on how to find the problem. There is no error message and logcat doesn't show any related errors. Are there any other ways to debug this problem? Or is this a known behaviour?

Im using Lineage 16.0 on an Sony Xperia XZ1Compact

**Comment by baldrianbandit** [comment]
I'm running Lineage 16 w/o Gapps.

There is a known bug that makes IchnaeaNlpBackend find no cells, see [https://github.com/microg/IchnaeaNlpBackend/issues/38](this issue). With wifi disabled,
`adb logcat | grep Ichnaea`
results in
`IchnaeaBackendService: Cells: 0`

The backend does resolve location by wifi, though. With wifi enabled, you should get `IchnaeaBackendService: request: {"wifiAccessPoints":[<wifi access points around you>])`
`IchnaeaBackendService: response: {"location": {"lat": <lat>, "lng": <lng>}, "accuracy": <acc>}`

**Comment by AllesMeins** [comment]
Thanks for the reply, but this doesn't seem to be the problem. I checked the log and there are access points around me in there and even my accurate location. But somehow this location does get lost somewhere along the way. I've added two logs - one is filtered by "nlp" and the other one by "Ichnaea". In both I removed my location and replaced it with XX,XXXXXX and YY,YYYYYY
[logcat_nlp.txt](https://github.com/microg/IchnaeaNlpBackend/files/3701802/logcat_nlp.txt)
[logcat_Ichnaea.txt](https://github.com/microg/IchnaeaNlpBackend/files/3701803/logcat_Ichnaea.txt)

**Comment by domkrm** [comment]
I had the same problem on OnePlus 3 with LOS 16 (MicroG). And I think I found the problem. The `CellInfo(s)` returned from `TelephonyManager.getAllCellInfo()` have no MNC (NULL). On a LG G6 with standard OS there is no problem. Unfortunaly I can't tell if it's a problem related to LOS or OnePlus 3. Maybe we can implement a fallback like in the LocalGSMBackend. There the MNC is retrieved with `TelephonyManager.getNetworkOperator()` if `TelephonyManager.getAllCellInfo()` provided no Cells with MNC.

**Comment by domkrm** [comment]
I made a POC and it worked good. But I think it's a problem related to the NLP API (https://github.com/microg/android_external_UnifiedNlpApi). So first I will make a pull request there. And then I can make a pull request for this backend with the new version of the API.

**Comment by domkrm** [comment]
I've continued to analyse the problem. I think it's not a device nor a LOS problem. It's an Android 9 problem in combination with MNCs with prefixed 0 (e.g. "01"). In Android 9 they changed some code in `CellIdentity`. The MNC is passed as integer to `CellIdentityLte/CellIdentityGsm` ("01" = 1). But in the super class `CellIdentity` the MNC is checked if 2- or 3-digit. And since it's not 2-digit, MNC is set to NULL.

**Comment by domkrm** [comment]
I have the same problem and after some analysing, testing and searching I found the following issue tracker entry: https://issuetracker.google.com/issues/113560852
It seems that this is a bug since Android 9 in combination with 0-prefixed MNCs (e.g. "01").
The last comment is "The issue has been fixed and it will become be available in a future Android release". I looked into the Android 10 source code and the bug still exists.

**Comment by Iey4iej3** [comment]
> I have the same problem and after some analysing, testing and searching I found the following issue tracker entry: https://issuetracker.google.com/issues/113560852
> It seems that this is a bug since Android 9 in combination with 0-prefixed MNCs (e.g. "01").
> The last comment is "The issue has been fixed and it will become be available in a future Android release". I looked into the Android 10 source code and the bug still exists.

Could you please ask them there (and don't mention the post here since Google would not be very happy about the existence of microG, say).

**Comment by Iey4iej3** [comment]
> I have the same problem and after some analysing, testing and searching I found the following issue tracker entry: https://issuetracker.google.com/issues/113560852
> It seems that this is a bug since Android 9 in combination with 0-prefixed MNCs (e.g. "01").
> The last comment is "The issue has been fixed and it will become be available in a future Android release". I looked into the Android 10 source code and the bug still exists.

This seems to be [fixed](https://android.googlesource.com/platform/frameworks/base/+/2c3a62d8784d372dbf2e3f48b2b5674d876e7a57%5E%21/telephony/java/android/telephony/CellIdentity.java) upstream but not fixed in the source code of LineageOS 17.

**Comment by domkrm** [comment]
> This seems to be [fixed](https://android.googlesource.com/platform/frameworks/base/+/2c3a62d8784d372dbf2e3f48b2b5674d876e7a57%5E%21/telephony/java/android/telephony/CellIdentity.java) upstream but not fixed in the source code of LineageOS 17 where I have just [committed](https://github.com/LineageOS/android_frameworks_base/commit/af317a226b1be063add9228bd084276b3e8e15f2).

Yes, I see this too. But I don't think this is fixed correctly. It's still checked if length of MNC is between 2 and 3.

```
private static final int MNC_MIN_LENGTH = 2;
private static final int MNC_MAX_LENGTH = 3;

if (mnc.length() < MNC_MIN_LENGTH || mnc.length() > MNC_MAX_LENGTH) return false;
```

I know that MNC must be 2- or 3-digits. But since the MNC is passed as INT to the constructors of the subclasses the 0-prefixed MNCs will be translated into 1-digit MNCs.

```
public CellIdentityLte(int mcc, int mnc, int ci, int pci, int tac) {
    this(ci, pci, tac, CellInfo.UNAVAILABLE, CellInfo.UNAVAILABLE, String.valueOf(mcc),
            String.valueOf(mnc), null, null);
}
```

**Comment by Iey4iej3** [comment]
> > This seems to be [fixed](https://android.googlesource.com/platform/frameworks/base/+/2c3a62d8784d372dbf2e3f48b2b5674d876e7a57%5E%21/telephony/java/android/telephony/CellIdentity.java) upstream but not fixed in the source code of LineageOS 17 where I have just [committed](https://github.com/LineageOS/android_frameworks_base/commit/af317a226b1be063add9228bd084276b3e8e15f2).
> 
> Yes, I see this too. But I don't think this is fixed correctly. It's still checked if length of MNC is between 2 and 3.
> 
> ```
> private static final int MNC_MIN_LENGTH = 2;
> private static final int MNC_MAX_LENGTH = 3;
> 
> if (mnc.length() < MNC_MIN_LENGTH || mnc.length() > MNC_MAX_LENGTH) return false;
> ```
> 
> I know that MNC must be 2- or 3-digits. But since the MNC is passed as INT to the constructors of the subclasses the 0-prefixed MNCs will be translated into 1-digit MNCs.
> 
> ```
> public CellIdentityLte(int mcc, int mnc, int ci, int pci, int tac) {
>     this(ci, pci, tac, CellInfo.UNAVAILABLE, CellInfo.UNAVAILABLE, String.valueOf(mcc),
>             String.valueOf(mnc), null, null);
> }
> ```

Maybe you need to add a comment there. By the way, I don't know what `@UnsupportedAppUsage(maxTargetSdk = Build.VERSION_CODES.P, trackingBug = 115609023)` means (the line preceding this method).

**Comment by domkrm** [comment]
> Maybe you need to add a comment there. By the way, I don't know what `@UnsupportedAppUsage(maxTargetSdk = Build.VERSION_CODES.P, trackingBug = 115609023)` means (the line preceding the construction method that you have quoted).
> 
> You can also commit at the LOS repo.

Sorry, I overlooked the second constructor in the subclasses.

```
public CellIdentityLte(int ci, int pci, int tac, int earfcn, int bandwidth, String mccStr,
        String mncStr, String alphal, String alphas) {
    super(TAG, CellInfo.TYPE_LTE, mccStr, mncStr, alphal, alphas);
...
}
```

Here the MNC is passed as STRING to the constructor.

But I don't get it where these constructors get called.

```@UnsupportedAppUsage``` means that App developers shouldn't rely on the following method, because it's only for internal use and could be changed anytime.

**Comment by Iey4iej3** [comment]
There seems a lot of constructors. By the way, do you know how often these codes are merged into LOS repo?

**Comment by domkrm** [comment]
> There seems a lot of constructors. By the way, do you know how often these codes are merged into LOS repo?

No, sorry. It's the first time I deal with the Android/LOS internal source code.

**Comment by kurt-by** [comment]
> 
> 
> > I have the same problem and after some analysing, testing and searching I found the following issue tracker entry: https://issuetracker.google.com/issues/113560852
> > It seems that this is a bug since Android 9 in combination with 0-prefixed MNCs (e.g. "01").
> > The last comment is "The issue has been fixed and it will become be available in a future Android release". I looked into the Android 10 source code and the bug still exists.
> 
> This seems to be [fixed](https://android.googlesource.com/platform/frameworks/base/+/2c3a62d8784d372dbf2e3f48b2b5674d876e7a57%5E%21/telephony/java/android/telephony/CellIdentity.java) upstream but not fixed in the source code of LineageOS 17 where I have just [committed](https://github.com/LineageOS/android_frameworks_base/commit/af317a226b1be063add9228bd084276b3e8e15f2).

Sorry, that's not how pull requests for LineageOS are done. They have ther code review in https://review.lineageos.org/q/status:open

**Comment by hkemal** [comment]
Hi people,
anything new concerning this bug?
I am on LineageOS 16 for uG and none of the NLP backends (Mozilla, DejaVu) work with cell identification.
Due to the fact that this seems to be an Andoroid 9 bug switching to another ROM will not get this working, right?
Regards
K

**Comment by baldrianbandit** [comment]
> Hi people,
> Regards
> K

Switching to microG and it's shipped UnifiedNlp can do the trick, at least when using LocalGSM network provider.
Refer to [this post](https://forum.xda-developers.com/showpost.php?p=81427023&postcount=817) in the Sony XZ1C LineageOS thread.

**Comment by domkrm** [comment]
> > Hi people,
> > Regards
> > K
> 
> Switching to microG and it's shipped UnifiedNlp can do the trick, at least when using LocalGSM network provider.
> Refer to [this post](https://forum.xda-developers.com/showpost.php?p=81427023&postcount=817) in the Sony XZ1C LineageOS thread.

LocalGSM provider should always work.
I take a look in the source code.
If it can't get a valid cell information then another approach is used to get a valid cell information.

**Comment by domkrm** [comment]
> Hi people,
> anything new concerning this bug?
> I am on LineageOS 16 for uG and none of the NLP backends (Mozilla, DejaVu) work with cell identification.
> Due to the fact that this seems to be an Andoroid 9 bug switching to another ROM will not get this working, right?
> Regards
> K

I made a pull request in the UnifiedNlpApi (https://github.com/microg/android_external_UnifiedNlpApi/pull/10) which has a workaround for the bug in Android 9.
It's already merged but I have to wait for @mar-v-in to make a new release.
Then we can update the backends which uses the Api.
And then a new release in the F-Droid is needed.

If you want you can install the attached APK.
It's the Mozilla Location Service with my fix included.
You must activate this backend in the microG settings (name is "Mozilla Location Service 2").

For me this fixed the problem and I successfully get a network location.

If you have tested it, please tell me if it workes for you also.

[org.microg.nlp.backend.ichnaea2.apk.zip](https://github.com/microg/IchnaeaNlpBackend/files/4041624/org.microg.nlp.backend.ichnaea2.apk.zip)

**Comment by baldrianbandit** [comment]
org.microg.nlp.backend.ichnaea2 keeps crashing on my LineageOS 16 device using microG Service Core 0.210.19420 and built in UnifiedNlp.

_But_ I get a network fix using the usual backend org.microg.nlp.backend.ichnaea in combination with microG Service Core, while org.microg.nlp.backend.ichnaea in combination with UnifiedNlp 1.6.8 without microG suffered from the MNC-prefix bug.

Grepping through the logcat, I am pretty sure to claim that the bug is not present using microG Service Core.

**Comment by anonimno1** [comment]
> 
> 
> > > Hi people,
> > > Regards
> > > K
> > 
> > 
> > Switching to microG and it's shipped UnifiedNlp can do the trick, at least when using LocalGSM network provider.
> > Refer to [this post](https://forum.xda-developers.com/showpost.php?p=81427023&postcount=817) in the Sony XZ1C LineageOS thread.
> 
> LocalGSM provider should always work.
> I take a look in the source code.
> If it can't get a valid cell information then another approach is used to get a valid cell information.

LocalGSM works, I confirmed this today.
This is interesting, because DejaVu does not work with cell information, although it is the same developer as LocalGSM.

**Comment by anonimno1** [comment]
> 
> 
> Thank you. org.microg.nlp.backend.ichnaea2 keeps crashing on my LineageOS 16 device using com.google.android.gms (microG Service Core 0.210.19420) and it's built in UnifiedNlp. I'm going to test it on org.microg.nlp (a.k.a UnifedNlp 1.6.8).

It crashes on my LOS 16 also. 
Today I wiped the LOSforuG and installed pure LOS.
Will also test if UnifiedNlp from F-Droid works.

**Comment by domkrm** [comment]
> Thank you. org.microg.nlp.backend.ichnaea2 keeps crashing on my LineageOS 16 device using com.google.android.gms (microG Service Core 0.210.19420) and it's built in UnifiedNlp. I'm going to test it on org.microg.nlp (a.k.a UnifedNlp 1.6.8).
> 
> Update:
> Crashes also when used together with org.microg.nlp.
> [log.txt](https://github.com/microg/IchnaeaNlpBackend/files/4045802/log.txt)

Could you please go into app settings of my app and give it the two permissions. They should be deactivated. After activation it should work without crashes.

**Comment by baldrianbandit** [comment]
> Could you please go into app settings of my app and give it the two permissions. They should be deactivated. After activation it should work without crashes.

Both permissions disabled and enabled (and repeated several times), also deleted /data/user/0/org.microg.nlp.backend.ichnaea2 and rebooted several times, but no luck.

**Comment by domkrm** [comment]
> > Could you please go into app settings of my app and give it the two permissions. They should be deactivated. After activation it should work without crashes.
> 
> Both permissions disabled and enabled (and repeated several times), also deleted /data/user/0/org.microg.nlp.backend.ichnaea2 and rebooted several times, but no luck.

Could you please retry it with the following APK?
I think I uploaded an old APK first.

[org.microg.nlp.backend.ichnaea2.apk.zip](https://github.com/microg/IchnaeaNlpBackend/files/4060714/org.microg.nlp.backend.ichnaea2.apk.zip)

**Comment by kurt-by** [comment]
> > > Could you please go into app settings of my app and give it the two permissions. They should be deactivated. After activation it should work without crashes.
> > 
> > 
> > Both permissions disabled and enabled (and repeated several times), also deleted /data/user/0/org.microg.nlp.backend.ichnaea2 and rebooted several times, but no luck.
> 
> Could you please retry it with the following APK?
> I think I uploaded an old APK first.
> 
> [org.microg.nlp.backend.ichnaea2.apk.zip](https://github.com/microg/IchnaeaNlpBackend/files/4060714/org.microg.nlp.backend.ichnaea2.apk.zip)

Sorry, does work on first try on superiorOS android 10 bacon. But stops to work after some time.

**Comment by baldrianbandit** [comment]
> Could you please retry it with the following APK?

Works quite well.  Repeated screen unlock / open SatStat / get network location fix / close SatStat / lock screen several times. Acquiring a location fix usually takes 5 to 20 seconds and grays out after some seconds, but that's fine. Log messages look good.

**Comment by kurt-by** [comment]
> > Could you please retry it with the following APK?
> 
> Works quite well. Repeated screen unlock / open SatStat / get network location fix / close SatStat / lock screen several times. Acquiring a location fix usually takes 5 to 20 seconds and grays out after some seconds, but that's fine. Log messages look good.

What phone/ROM?

**Comment by y0va** [comment]
Yay, first time I got Ichnaea to work. Could you provide a merge request for that?
